#!/bin/bash

KITHOME="/home/joe/lib/305/slug/devkitadv"

# ensure that at least one input file was passed
if [ $# -lt 1 ] 
then
  echo "Usage: $(basename $0) input.c"
  exit
fi

# for each argument
for f in $*
do
    # get base name and extension
    base=$(basename "$f")
    extension="${base##*.}"
    base="${base%.*}"

    # if it's a C file, compile it
    if [ "$extension" = "c" ]
    then
        $KITHOME/bin/arm-agb-elf-gcc -c -O3 -std=c99 "$base.$extension"
    fi

    # if it's a S file, assemble it
    if [ "$extension" = "s" ]
    then
        $KITHOME/bin/arm-agb-elf-gcc -c "$base.$extension"
    fi
done

# now link all the .o files we have
$KITHOME/bin/arm-agb-elf-gcc -O3 -nostartfiles $KITHOME/arm-agb-elf/lib/crt0.o -o program.elf *.o -lm
$KITHOME/bin/arm-agb-elf-objcopy -O binary program.elf program.gba

# get rid of temp files
rm -f *.o *.elf

